/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      borderRadius: {
        "2xl": "var(--radius)",
        xl: "var(--radius)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "#ffffff",
        },
        input: "var(--input)",
        ring: "var(--ring)",
        cloud: {
          DEFAULT: "var(--color-cloud)",
          light: "var(--color-cloud-light)",
          dark: "var(--color-cloud-dark)",
          hover: "var(--color-cloud-hover)",
          5: "var(--color-cloud-5)",
          10: "var(--color-cloud-10)",
          20: "var(--color-cloud-20)",
          30: "var(--color-cloud-30)",
          50: "var(--color-cloud-50)",
          80: "var(--color-cloud-80)",
        },
        local: {
          DEFAULT: "var(--color-local)",
          light: "var(--color-local-light)",
          dark: "var(--color-local-dark)",
          hover: "var(--color-local-hover)",
          5: "var(--color-local-5)",
          10: "var(--color-local-10)",
          15: "var(--color-local-15)",
          20: "var(--color-local-20)",
          30: "var(--color-local-30)",
          40: "var(--color-local-40)",
          50: "var(--color-local-50)",
          60: "var(--color-local-60)",
          80: "var(--color-local-80)",
        },
        surface: {
          primary: "var(--color-bg-primary)",
          secondary: "var(--color-bg-secondary)",
          tertiary: "var(--color-bg-tertiary)",
          surface: "var(--color-bg-surface)",
          overlay: "var(--color-bg-overlay)",
          elevated: "var(--color-bg-elevated)",
          "elevated-hover": "var(--color-bg-elevated-hover)",
          hover: "var(--color-bg-hover)",
        },
        border: {
          primary: "var(--color-border-primary)",
          secondary: "var(--color-border-secondary)",
          hover: "var(--color-border-hover)",
        },
        content: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          disabled: "var(--color-text-disabled)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          foreground: "var(--accent-foreground)",
          light: "var(--color-accent-light)",
          dark: "var(--color-accent-dark)",
          hover: "var(--color-accent-hover)",
          5: "var(--color-accent-5)",
          10: "var(--color-accent-10)",
          20: "var(--color-accent-20)",
          30: "var(--color-accent-30)",
          50: "var(--color-accent-50)",
          80: "var(--color-accent-80)",
        },
        success: "var(--color-success)",
        error: "var(--color-error)",
        warning: "var(--color-warning)",
        info: "var(--color-info)",
      },
    },
  },
  plugins: [],
};
