/* eslint-disable */
// @ts-nocheck
import type { Animation } from "./eyes-types";

const animations: Animation[] = [
  {
    name: "blink",
    description: "Quick natural blink",
    duration: 240,
    trigger: "click",
    priority: 10,
    tags: ["basic", "idle"],
    keyframes: [
      { at: 0, eyes: { sy: 1 } },
      { at: 80, eyes: { sy: 0.05 }, ease: "ease-in" },
      { at: 240, eyes: { sy: 1 }, ease: "ease-out" },
    ],
  },
  {
    name: "happy",
    description: "Eyes squish into happy arcs",
    duration: 1400,
    trigger: "dblclick",
    priority: 30,
    tags: ["emotion", "positive"],
    keyframes: [
      { at: 0, eyes: { sy: 1, h: 80, r: 16 } },
      { at: 200, eyes: { sy: 1, h: 40, r: "40px 40px 8px 8px", y: 8 }, ease: "spring" },
      { at: 1100, eyes: { sy: 1, h: 40, r: "40px 40px 8px 8px", y: 8 } },
      { at: 1400, eyes: { sy: 1, h: 80, r: 16, y: 0 }, ease: "ease-out" },
    ],
  },
  {
    name: "cracked-happy",
    description: "Happy eyes with glass crack effect",
    duration: 2000,
    priority: 35,
    tags: ["emotion", "positive", "effect"],
    keyframes: [
      { at: 0, eyes: { sy: 1, h: 80, r: 16 } },
      { at: 200, eyes: { sy: 1, h: 40, r: "40px 40px 8px 8px", y: 8 }, ease: "spring" },
      { at: 400, eyes: { sy: 1, h: 40, r: "40px 40px 8px 8px", y: 8 } },
      { at: 1600, eyes: { sy: 1, h: 40, r: "40px 40px 8px 8px", y: 8 } },
      { at: 2000, eyes: { sy: 1, h: 80, r: 16, y: 0 }, ease: "ease-out" },
    ],
  },
  {
    name: "surprised",
    description: "Eyes go wide",
    duration: 1200,
    trigger: "mouseenter",
    priority: 20,
    tags: ["emotion", "reaction"],
    keyframes: [
      { at: 0, eyes: { w: 80, h: 80, r: 16 } },
      { at: 120, eyes: { w: 100, h: 100, r: 20 }, gap: 80, ease: "spring" },
      { at: 900, eyes: { w: 100, h: 100, r: 20 }, gap: 80 },
      { at: 1200, eyes: { w: 80, h: 80, r: 16 }, gap: 60, ease: "ease-out" },
    ],
  },
  {
    name: "love",
    description: "Heart-shaped eyes",
    duration: 2000,
    priority: 35,
    tags: ["emotion", "positive", "viral"],
    keyframes: [
      { at: 0, eyes: { w: 80, h: 80, r: 16 } },
      { at: 100, eyes: { w: 0, h: 0 }, ease: "ease-in" },
      { at: 350, eyes: { w: 80, h: 80, r: 16, color: "#ff2d55" }, ease: "spring" },
      { at: 1600, eyes: { w: 80, h: 80, r: 16, color: "#ff2d55" } },
      { at: 1800, eyes: { w: 0, h: 0, color: "#ff2d55" }, ease: "ease-in" },
      { at: 2000, eyes: { w: 80, h: 80, r: 16, rot: 0 }, ease: "ease-out" },
    ],
  },
  {
    name: "wink",
    description: "Right eye winks",
    duration: 500,
    trigger: "contextmenu",
    priority: 15,
    tags: ["playful", "gesture"],
    keyframes: [
      { at: 0, eyes: { sy: 1 } },
      { at: 100, right: { sy: 0.05 }, ease: "ease-in" },
      { at: 350, right: { sy: 0.05 } },
      { at: 500, right: { sy: 1 }, ease: "ease-out" },
    ],
  },
  {
    name: "sad",
    description: "Droopy sad eyes",
    duration: 1700,
    trigger: "mouseleave",
    priority: 20,
    tags: ["emotion", "negative"],
    keyframes: [
      { at: 0, eyes: { h: 80, w: 80, r: 16, y: 0 } },
      { at: 300, eyes: { h: 50, w: 70, r: "8px 8px 20px 20px", y: 10 }, ease: "ease" },
      { at: 1300, eyes: { h: 50, w: 70, r: "8px 8px 20px 20px", y: 10 } },
      { at: 1700, eyes: { h: 80, w: 80, r: 16, y: 0 }, ease: "ease-out" },
    ],
  },
  {
    name: "angry",
    description: "Narrow angry glare",
    duration: 1200,
    trigger: "wheel",
    priority: 40,
    tags: ["emotion", "negative"],
    keyframes: [
      { at: 0, eyes: {} },
      { at: 200, eyes: { h: 50, w: 90, r: 8, y: 4 }, left: { rot: 8 }, right: { rot: -8 }, ease: "ease-in" },
      { at: 900, eyes: { h: 50, w: 90, r: 8, y: 4 }, left: { rot: 8 }, right: { rot: -8 } },
      { at: 1200, eyes: { h: 80, w: 80, r: 16, y: 0, rot: 0 }, ease: "ease-out" },
    ],
  },
  {
    name: "sleepy",
    description: "Eyes slowly droop closed",
    duration: 3500,
    priority: 5,
    tags: ["state", "idle"],
    keyframes: [
      { at: 0, eyes: { sy: 1, y: 0 } },
      { at: 500, eyes: { sy: 0.5, y: 4 }, ease: "ease" },
      { at: 1000, eyes: { sy: 0.3, y: 7 }, ease: "ease" },
      { at: 1500, eyes: { sy: 0.05, y: 10 }, ease: "ease" },
      { at: 2800, eyes: { sy: 0.05, y: 10 } },
      { at: 3500, eyes: { sy: 1, y: 0 }, ease: "spring" },
    ],
  },
  {
    name: "squint",
    description: "Narrow suspicious squint",
    duration: 1000,
    priority: 15,
    tags: ["emotion", "reaction"],
    keyframes: [
      { at: 0, eyes: {} },
      { at: 150, eyes: { h: 28, w: 90, r: 6, y: 2 }, ease: "ease" },
      { at: 750, eyes: { h: 28, w: 90, r: 6, y: 2 } },
      { at: 1000, eyes: { h: 80, w: 80, r: 16, y: 0 }, ease: "ease-out" },
    ],
  },
  {
    name: "dizzy",
    description: "Spiral dizzy motion",
    duration: 1200,
    priority: 25,
    tags: ["effect", "playful"],
    keyframes: [
      { at: 0, eyes: { x: 0, y: 0, w: 80, h: 80, r: 16 } },
      { at: 100, eyes: { x: 8, y: 0, w: 85, h: 70, r: 14 }, ease: "linear" },
      { at: 200, eyes: { x: 8, y: 8, w: 70, h: 85, r: 18 }, ease: "linear" },
      { at: 300, eyes: { x: 0, y: 8, w: 85, h: 70, r: 12 }, ease: "linear" },
      { at: 400, eyes: { x: -8, y: 0, w: 70, h: 85, r: 20 }, ease: "linear" },
      { at: 500, eyes: { x: -8, y: -8, w: 90, h: 65, r: 14 }, ease: "linear" },
      { at: 600, eyes: { x: 0, y: -8, w: 65, h: 90, r: 22 }, ease: "linear" },
      { at: 700, eyes: { x: 8, y: 0, w: 85, h: 75, r: 16 }, ease: "linear" },
      { at: 800, eyes: { x: 0, y: 0, w: 85, h: 85, r: 50 }, ease: "ease-out" },
      { at: 1000, eyes: { x: 0, y: 0, w: 85, h: 85, r: 50 } },
      { at: 1200, eyes: { x: 0, y: 0, w: 80, h: 80, r: 16 }, ease: "ease-out" },
    ],
  },
  {
    name: "look-left",
    description: "Eyes shift left",
    duration: 1000,
    priority: 10,
    tags: ["directional"],
    keyframes: [
      { at: 0, eyes: { x: 0, w: 80 } },
      { at: 200, eyes: { x: -16, w: 72, r: "16px 8px 8px 16px" }, ease: "ease-out" },
      { at: 700, eyes: { x: -16, w: 72, r: "16px 8px 8px 16px" } },
      { at: 1000, eyes: { x: 0, w: 80, r: 16 }, ease: "ease" },
    ],
  },
  {
    name: "look-right",
    description: "Eyes shift right",
    duration: 1000,
    priority: 10,
    tags: ["directional"],
    keyframes: [
      { at: 0, eyes: { x: 0, w: 80 } },
      { at: 200, eyes: { x: 16, w: 72, r: "8px 16px 16px 8px" }, ease: "ease-out" },
      { at: 700, eyes: { x: 16, w: 72, r: "8px 16px 16px 8px" } },
      { at: 1000, eyes: { x: 0, w: 80, r: 16 }, ease: "ease" },
    ],
  },
  {
    name: "shake",
    description: "Rapid horizontal shake - saying no",
    duration: 800,
    priority: 20,
    tags: ["gesture", "negative"],
    keyframes: [
      { at: 0, eyes: { x: 0 } },
      { at: 80, eyes: { x: -14 }, ease: "linear" },
      { at: 160, eyes: { x: 14 }, ease: "linear" },
      { at: 240, eyes: { x: -14 }, ease: "linear" },
      { at: 320, eyes: { x: 14 }, ease: "linear" },
      { at: 400, eyes: { x: -10 }, ease: "linear" },
      { at: 480, eyes: { x: 10 }, ease: "linear" },
      { at: 560, eyes: { x: -5 }, ease: "linear" },
      { at: 640, eyes: { x: 5 }, ease: "linear" },
      { at: 800, eyes: { x: 0 }, ease: "ease-out" },
    ],
  },
  {
    name: "glitch",
    description: "Digital glitch effect",
    duration: 900,
    priority: 40,
    tags: ["effect", "digital"],
    keyframes: [
      { at: 0, eyes: { w: 80, h: 80, r: 16, color: "currentColor" } },
      { at: 60, eyes: { w: 120, h: 20, x: -20, color: "#00ffff" }, ease: "linear" },
      { at: 120, eyes: { w: 40, h: 90, x: 15, color: "#ff00ff" }, ease: "linear" },
      { at: 180, eyes: { w: 100, h: 30, x: -10, y: -10, color: "currentColor" }, ease: "linear" },
      { at: 240, eyes: { w: 50, h: 100, x: 20, y: 5, color: "#00ffff" }, ease: "linear" },
      { at: 300, eyes: { w: 80, h: 10, x: -15, color: "#ff00ff" }, ease: "linear" },
      { at: 360, eyes: { w: 10, h: 80, x: 10, color: "currentColor" }, ease: "linear" },
      { at: 420, eyes: { w: 90, h: 50, x: -5, y: -8, color: "#00ffff" }, ease: "linear" },
      { at: 500, eyes: { w: 60, h: 60, r: 50, x: 0, y: 0, color: "#ff00ff" }, ease: "linear" },
      { at: 600, eyes: { w: 80, h: 80, r: 16, x: 0, y: 0, color: "currentColor", sy: 0.05 }, ease: "linear" },
      { at: 700, eyes: { sy: 1 }, ease: "linear" },
      { at: 900, eyes: { w: 80, h: 80, r: 16, x: 0, y: 0, color: "currentColor", sy: 1 }, ease: "ease-out" },
    ],
  },
  {
    name: "bounce",
    description: "Rapid vertical bounce",
    duration: 1200,
    priority: 15,
    tags: ["physics", "playful"],
    keyframes: [
      { at: 0, eyes: { y: 0, sy: 1 } },
      { at: 100, eyes: { y: -20, sy: 1.1 }, ease: "ease-out" },
      { at: 200, eyes: { y: 4, sy: 0.85 }, ease: "ease-in" },
      { at: 300, eyes: { y: 0, sy: 1 }, ease: "ease-out" },
      { at: 400, eyes: { y: -14, sy: 1.06 }, ease: "ease-out" },
      { at: 500, eyes: { y: 3, sy: 0.9 }, ease: "ease-in" },
      { at: 600, eyes: { y: 0, sy: 1 }, ease: "ease-out" },
      { at: 750, eyes: { y: -8, sy: 1.03 }, ease: "ease-out" },
      { at: 850, eyes: { y: 0, sy: 1 }, ease: "ease" },
      { at: 1200, eyes: { y: 0, sy: 1 } },
    ],
  },
  {
    name: "roll",
    description: "Eyes roll in circles",
    duration: 2000,
    priority: 25,
    tags: ["gesture", "sarcastic"],
    keyframes: [
      { at: 0, eyes: { x: 0, y: 0 } },
      { at: 250, eyes: { x: 0, y: -12 }, ease: "ease" },
      { at: 500, eyes: { x: 12, y: -12 }, ease: "ease" },
      { at: 750, eyes: { x: 12, y: 0 }, ease: "ease" },
      { at: 1000, eyes: { x: 12, y: 12 }, ease: "ease" },
      { at: 1250, eyes: { x: 0, y: 12 }, ease: "ease" },
      { at: 1500, eyes: { x: -12, y: 12 }, ease: "ease" },
      { at: 1750, eyes: { x: -12, y: 0 }, ease: "ease" },
      { at: 2000, eyes: { x: 0, y: 0 }, ease: "ease" },
    ],
  },
  {
    name: "scared",
    description: "Wide scared eyes with shake",
    duration: 1500,
    priority: 30,
    tags: ["emotion", "reaction"],
    keyframes: [
      { at: 0, eyes: { w: 80, h: 80, r: 16 } },
      { at: 100, eyes: { w: 100, h: 100, r: 50 }, gap: 90, ease: "spring" },
      { at: 200, eyes: { x: -3 }, ease: "linear" },
      { at: 250, eyes: { x: 3 }, ease: "linear" },
      { at: 300, eyes: { x: -3 }, ease: "linear" },
      { at: 350, eyes: { x: 3 }, ease: "linear" },
      { at: 400, eyes: { x: -2 }, ease: "linear" },
      { at: 450, eyes: { x: 2 }, ease: "linear" },
      { at: 500, eyes: { x: 0 }, ease: "linear" },
      { at: 1200, eyes: { w: 100, h: 100, r: 50 }, gap: 90 },
      { at: 1500, eyes: { w: 80, h: 80, r: 16, x: 0 }, gap: 60, ease: "ease-out" },
    ],
  },
  {
    name: "thinking",
    description: "Eyes look up and to the side",
    duration: 2000,
    priority: 15,
    tags: ["gesture", "contemplative"],
    keyframes: [
      { at: 0, eyes: { x: 0, y: 0 } },
      { at: 300, eyes: { x: 10, y: -8, w: 75 }, ease: "ease-out" },
      { at: 1700, eyes: { x: 10, y: -8, w: 75 } },
      { at: 2000, eyes: { x: 0, y: 0, w: 80 }, ease: "ease" },
    ],
  },
  {
    name: "excited",
    description: "Eyes grow and sparkle",
    duration: 1600,
    priority: 30,
    tags: ["emotion", "positive"],
    keyframes: [
      { at: 0, eyes: { w: 80, h: 80, r: 16, sy: 1 } },
      { at: 200, eyes: { w: 95, h: 95, r: 20, sy: 1.1 }, gap: 70, ease: "spring" },
      { at: 300, eyes: { sy: 0.05 }, ease: "ease-in" },
      { at: 400, eyes: { sy: 1.1 }, ease: "ease-out" },
      { at: 500, eyes: { sy: 0.05 }, ease: "ease-in" },
      { at: 600, eyes: { sy: 1.1 }, ease: "ease-out" },
      { at: 1300, eyes: { w: 95, h: 95, r: 20, sy: 1.1 }, gap: 70 },
      { at: 1600, eyes: { w: 80, h: 80, r: 16, sy: 1 }, gap: 60, ease: "ease-out" },
    ],
  },
  {
    name: "gunshot",
    description: "Iconic x_x death animation with screen shatter",
    duration: 3500,
    priority: 100,
    tags: ["viral", "meme", "iconic", "death"],
    keyframes: [
      { at: 0, eyes: { w: 80, h: 80, r: 16, sy: 1, rot: 0 } },
      { at: 60, eyes: { w: 6, h: 6, r: 50 }, ease: "ease-in" },
      { at: 160, eyes: { w: 60, h: 10, r: 3, rot: 45 }, ease: "linear" },
      { at: 260, eyes: { w: 10, h: 60, r: 3, rot: 45 }, ease: "linear" },
      { at: 360, eyes: { w: 60, h: 10, r: 3, rot: -45 }, ease: "linear" },
      { at: 460, eyes: { w: 10, h: 60, r: 3, rot: -45 }, ease: "linear" },
      { at: 560, eyes: { w: 60, h: 10, r: 3, rot: 45 }, ease: "linear" },
      { at: 660, eyes: { w: 10, h: 60, r: 3, rot: 45 } },
      { at: 1800, eyes: { w: 10, h: 60, r: 3, rot: 45 } },
      { at: 2200, eyes: { w: 10, h: 60, r: 3, rot: 45, y: 120, sy: 0 }, ease: "ease-in" },
      { at: 3000, eyes: { w: 10, h: 60, r: 3, rot: 45, y: 120, sy: 0 } },
      { at: 3500, eyes: { w: 80, h: 80, r: 16, rot: 0, y: 0, sy: 1 }, ease: "spring" },
    ],
  },
];

export function getAllAnimations(): Animation[] {
  return [...animations];
}

export function getAnimation(name: string): Animation | undefined {
  return animations.find((a) => a.name === name);
}

export function getAnimationsByTrigger(trigger: string): Animation[] {
  return animations.filter((a) => a.trigger === trigger);
}

export function getAnimationByKey(key: string): Animation | undefined {
  return animations.find((a) => a.key === key);
}
