export type TranscriptionRecord = {
  id: string;
  timestamp: string;
  text: string;
  raw_text?: string | null;
  audio_path: string;
  audio_available: boolean;
  status: "success" | "error";
  error_message?: string;
  llm_cleaned: boolean;
  speech_model: string;
  llm_model?: string | null;
  word_count: number;
  audio_duration_seconds: number;
  synced: boolean;
  mode_id?: string | null;
  mode_name?: string | null;
  stt_elapsed_ms?: number | null;
  cleanup_elapsed_ms?: number | null;
  paste_elapsed_ms?: number | null;
  total_elapsed_ms?: number | null;
  auto_paste_requested: boolean;
  auto_paste_succeeded?: boolean | null;
  auto_transform_preset_id?: string | null;
  auto_transform_label?: string | null;
};
