use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use super::{
    FridayArtifactCheckpoint, FridayArtifactKind, FridayArtifactRecord, FridayCheckpointReason,
    FridayPreviewRunner,
};
use crate::models::GlmOcr;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum FridayOcrSmokeStatus {
    Passed,
    Failed,
}

impl FridayOcrSmokeStatus {
    pub fn label(self) -> &'static str {
        match self {
            Self::Passed => "passed",
            Self::Failed => "failed",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FridayOcrSmokeReport {
    pub generated_at_unix_ms: u128,
    pub status: FridayOcrSmokeStatus,
    pub output_dir: String,
    pub image_source: String,
    pub model_execution: bool,
    pub model_paths: Vec<String>,
    pub artifact_json: String,
    pub checkpoint_json: String,
    pub output_markdown: String,
    pub report_json: String,
    pub artifact: FridayArtifactRecord,
    pub checkpoint: FridayArtifactCheckpoint,
    pub extracted_text_preview: String,
    pub findings: Vec<String>,
}

impl FridayOcrSmokeReport {
    pub fn to_pretty_json(&self) -> serde_json::Result<String> {
        serde_json::to_string_pretty(self)
    }
}

pub fn run_friday_ocr_smoke(
    output_dir: impl AsRef<Path>,
    image_path: Option<&str>,
    execute_model: bool,
) -> Result<FridayOcrSmokeReport> {
    let output_dir = output_dir.as_ref();
    fs::create_dir_all(output_dir)
        .with_context(|| format!("failed to create OCR smoke dir {}", output_dir.display()))?;

    let generated_at_unix_ms = unix_ms();
    let image_source = image_path
        .map(str::to_string)
        .unwrap_or_else(|| "fixture://friday-ocr-smoke".to_string());
    let model_paths = GlmOcr::resolved_model_paths()
        .iter()
        .map(|path| path.to_string_lossy().into_owned())
        .collect::<Vec<_>>();

    let extracted_text = if execute_model {
        let image_path = image_path.context("OCR smoke execution requires an image path")?;
        GlmOcr::new()?.ocr_image(image_path)?
    } else {
        "Friday OCR smoke fixture\nLocal multimodal artifacts stay on this machine.\nGenerated by the bounded smoke path."
            .to_string()
    };

    let status = if extracted_text.trim().is_empty() {
        FridayOcrSmokeStatus::Failed
    } else {
        FridayOcrSmokeStatus::Passed
    };
    let output_markdown = output_dir.join("ocr-smoke-output.md");
    let artifact_json = output_dir.join("ocr-smoke-artifact.json");
    let checkpoint_json = output_dir.join("ocr-smoke-checkpoint.json");
    let report_json = output_dir.join("ocr-smoke-report.json");
    let artifact_id = "ocr-smoke-output".to_string();
    let checkpoint_id = "ocr-smoke-output-cp1".to_string();

    let markdown = format!(
        "# Friday OCR Smoke Output\n\n- Source: `{}`\n- Model execution: `{}`\n- Status: `{}`\n\n## Extracted Text\n\n{}\n",
        image_source,
        execute_model,
        status.label(),
        extracted_text.trim()
    );
    fs::write(&output_markdown, markdown)
        .with_context(|| format!("failed to write {}", output_markdown.display()))?;

    let artifact = FridayArtifactRecord {
        id: artifact_id.clone(),
        project_id: "friday-local".to_string(),
        kind: FridayArtifactKind::Markdown,
        title: "OCR smoke output".to_string(),
        path: output_markdown.to_string_lossy().into_owned(),
        language: Some("markdown".to_string()),
        preview_runner: FridayPreviewRunner::Markdown,
        current_checkpoint_id: checkpoint_id.clone(),
        created_at_unix_ms: generated_at_unix_ms,
        updated_at_unix_ms: generated_at_unix_ms,
    };
    let checkpoint = FridayArtifactCheckpoint {
        id: checkpoint_id,
        artifact_id,
        reason: if execute_model {
            FridayCheckpointReason::Generated
        } else {
            FridayCheckpointReason::Created
        },
        summary: if execute_model {
            "OCR smoke artifact generated from a local image.".to_string()
        } else {
            "OCR smoke artifact generated from the built-in fixture.".to_string()
        },
        content_hash: stable_hash(&extracted_text),
        created_at_unix_ms: generated_at_unix_ms,
    };

    write_json(&artifact_json, &artifact)?;
    write_json(&checkpoint_json, &checkpoint)?;

    let findings = if status == FridayOcrSmokeStatus::Passed {
        Vec::new()
    } else {
        vec!["OCR smoke produced no extracted text.".to_string()]
    };
    let report = FridayOcrSmokeReport {
        generated_at_unix_ms,
        status,
        output_dir: output_dir.to_string_lossy().into_owned(),
        image_source,
        model_execution: execute_model,
        model_paths,
        artifact_json: artifact_json.to_string_lossy().into_owned(),
        checkpoint_json: checkpoint_json.to_string_lossy().into_owned(),
        output_markdown: output_markdown.to_string_lossy().into_owned(),
        report_json: report_json.to_string_lossy().into_owned(),
        artifact,
        checkpoint,
        extracted_text_preview: extracted_text
            .split_whitespace()
            .take(32)
            .collect::<Vec<_>>()
            .join(" "),
        findings,
    };
    write_json(&report_json, &report)?;

    Ok(report)
}

fn stable_hash(input: &str) -> String {
    let mut hash: u64 = 0xcbf29ce484222325;
    for byte in input.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{hash:016x}")
}

fn write_json<T: Serialize>(path: &Path, value: &T) -> Result<()> {
    let json = serde_json::to_string_pretty(value)?;
    fs::write(path, json).with_context(|| format!("failed to write {}", path.display()))
}

fn unix_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn ocr_smoke_writes_artifact_checkpoint_and_report() {
        let root = std::env::temp_dir().join(format!(
            "friday-ocr-smoke-{}-{}",
            std::process::id(),
            unix_ms()
        ));
        let _ = fs::remove_dir_all(&root);

        let report = run_friday_ocr_smoke(&root, None, false).unwrap();
        assert_eq!(report.status, FridayOcrSmokeStatus::Passed);
        assert!(!report.model_execution);
        assert!(PathBuf::from(&report.artifact_json).exists());
        assert!(PathBuf::from(&report.checkpoint_json).exists());
        assert!(PathBuf::from(&report.output_markdown).exists());
        assert!(PathBuf::from(&report.report_json).exists());
        assert_eq!(report.artifact.id, "ocr-smoke-output");
        assert_eq!(report.checkpoint.artifact_id, report.artifact.id);
        assert_eq!(report.artifact.current_checkpoint_id, report.checkpoint.id);
        assert_eq!(report.artifact.preview_runner, FridayPreviewRunner::Markdown);

        let _ = fs::remove_dir_all(&root);
    }
}
